[project]
name = "llm-health-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "google-generativeai>=0.8.5",
    "openai>=1.95.1",
    "requests>=2.32.4",
    "uvicorn>=0.35.0",
]
